spring:
  datasource:
    url: ${NEON_DB_URL}
    username: ${NEON_DB_USERNAME}
    password: ${NEON_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 16

  flyway:
    enabled: true
    baseline-on-migrate: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  rabbitmq:
    host: localhost
    port: 5672
