package com.medchart.ehr.domain.provider;

public enum ProviderType {
    PHYSICIAN,
    NURSE_PRACTITIONER,
    PHYSICIAN_ASSISTANT,
    REGISTERED_NURSE,
    LICENSED_PRACTICAL_NURSE,
    CERTIFIED_NURSING_ASSISTANT,
    PHARMACIST,
    PHYSICAL_THERAPIST,
    OCCUPATIONAL_THERAPIST,
    RESPIRATORY_THERAPIST,
    SOCIAL_WORKER,
    CASE_MANAGER,
    DIETITIAN,
    PSYCHOLOGIST,
    PSYCHIATRIST,
    MEDICAL_ASSISTANT,
    OTHER
}
